### ISSUE TITLE
README: project logo is not visible in light theme

### ISSUE THREAD

**Issue by HugooB** [opencybersecurityalliance/cacao-roaster#2]
First of all, great work! Beautiful piece of software, very excited to easily generate CACAO playbooks with it.
I was reading the documentation and noticed that the project logo is in white and displayed on a white background, making it invisible to the end user. Here is a screenshot showing this behaviour:

![Screenshot 2024-01-19 at 13 09 33](https://github.com/opencybersecurityalliance/cacao-roaster/assets/14057134/d9a128df-3f34-42cb-9490-703b8dbeeb48)

Maybe it would be nice to create a coloured version of the logo to be used here?

**Comment by mateusdz** [comment]
We have updated the logo, thanks. 
(https://github.com/opencybersecurityalliance/cacao-roaster/pull/5)
